### ISSUE TITLE
GET '/v3/users/{user_id}/project_roles' should be protected ?

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keystone-spassword#113]
also GET /v3/users/<user_id>/checkemail

**Comment by fgalan** [comment]
What about POST /v3/users/<user_id>/sndfa? Is is already protected? Should be (I guess so)?

**Comment by fgalan** [comment]
With regards to GET /v3/users/<user_id>/checkemail (and maybe POST /v3/users/<user_id>/sndfa), maybe the documentation in https://github.com/telefonicaid/fiware-keystone-spassword/blob/master/docs/second_factor_auth.md should be updated to explicitly tell for the operations that are using x-auth-token to whom user that token must belong. I mean, for instance:

> This call uses a x-auth-token associated to `<user_id>` user.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-keystone-spassword/pull/118. Should it be closed?
