### ISSUE TITLE
docker env vars for spassword options

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keystone-spassword#116]
For the following options:
```
enabled=true
pwd_max_tries=5
pwd_block_minutes=30
pwd_exp_days=365
pwd_user_blacklist=
smtp_server='0.0.0.0'
smtp_port=587
smtp_tls=true
smtp_user='smtpuser@yourdomain.com'
smtp_password='yourpassword'
smtp_from='smtpuser'
sndfa=false
sndfa_endpoint='localhost:5001'
sndfa_time_window=24
```

**Comment by AlvaroVega** [comment]
[[ "${SPASSWORD_ENABLED}" == "" ]] && export SPASSWORD_ENABLED=True
[[ "${SPASSWORD_PWD_MAX_TRIES}" == "" ]] && export SPASSWORD_PWD_MAX_TRIES=5
[[ "${SPASSWORD_PWD_BLOCK_MINUTES}" == "" ]] && export SPASSWORD_PWD_BLOCK_MINUTES=30
[[ "${SPASSWORD_PWD_EXP_DAYS}" == "" ]] && export SPASSWORD_PWD_EXP_DAYS=365
[[ "${SPASSWORD_SMTP_SERVER}" == "" ]] && export SPASSWORD_SMTP_SERVER='0.0.0.0'
[[ "${SPASSWORD_SMTP_PORT}" == "" ]] && export SPASSWORD_SMTP_PORT=587
[[ "${SPASSWORD_SMTP_TLS}" == "" ]] && export SPASSWORD_SMTP_TLS=True
[[ "${SPASSWORD_SMTP_USER}" == "" ]] && export SPASSWORD_SMTP_USER='smtpuser@yourdomain.com'
[[ "${SPASSWORD_SMTP_PASSWORD}" == "" ]] && export SPASSWORD_SMTP_PASSWORD='yourpassword'
[[ "${SPASSWORD_SMTP_FROM}" == "" ]] && export SPASSWORD_SMTP_FROM='smtpuser'
[[ "${SPASSWORD_SNDFA}" == "" ]] && export SPASSWORD_SNDFA=False
[[ "${SPASSWORD_SNDFA_ENDPOINT}" == "" ]] && export SPASSWORD_SNDFA_ENDPOINT='localhost:5001'
[[ "${SPASSWORD_SNDFA_TIME_WINDOW}" == "" ]] && export SPASSWORD_SNDFA_TIME_WINDOW=24

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-keystone-spassword/pull/119. Should it be closed?
