### ISSUE TITLE
GET /v3/users/{user_id}/project_roles with a non admin user results 403

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keystone-spassword#123]
comes from https://github.com/telefonicaid/fiware-keystone-spassword/pull/118

^[[Aiot-keystone                | 2019-12-17 09:17:04.153 122 INFO keystone.common.wsgi [req-7ddb2f62-1815-4cf9-95a8-2ff2bfb3fd6f 48cfe82db405468ea124647c398b3894 - 2d11ea01a00c423b919cb336adb99c76 2d11ea01a00c423b919cb336adb99c76 -] GET http://localhost:5001/v3/users/48cfe82db405468ea124647c398b3894/project_roles
iot-keystone                | 2019-12-17 09:17:04.154 122 WARNING keystone.common.wsgi [req-7ddb2f62-1815-4cf9-95a8-2ff2bfb3fd6f 48cfe82db405468ea124647c398b3894 - 2d11ea01a00c423b919cb336adb99c76 2d11ea01a00c423b919cb336adb99c76 -] You are not authorized to perform the requested action: identity:get_project_roles
iot-keystone                | 2019-12-17 09:17:04.157 122 INFO eventlet.wsgi.server [req-7ddb2f62-1815-4cf9-95a8-2ff2bfb3fd6f 48cfe82db405468ea124647c398b3894 - 2d11ea01a00c423b919cb336adb99c76 2d11ea01a00c423b919cb336adb99c76 -] 172.17.0.1 - - [17/Dec/2019 09:17:04] "GET /v3/users/48cfe82db405468ea124647c398b3894/project_roles HTTP/1.1" 403 345 0.012655

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-keystone-spassword/pull/124
