### ISSUE TITLE
log into stdout

### ISSUE THREAD

**Issue by IvanHdzC** [telefonicaid/fiware-keystone-spassword#148]
Currently Keystone logs into a file which outputs through a tail. It should log directly to stdout.

**Comment by AlvaroVega** [comment]
Maybe solution should reached tunning logging.conf file: https://docs.openstack.org/keystone/pike/configuration/samples/logging-conf.html (i.e. disabling file logging)

**Comment by AlvaroVega** [comment]
done in https://github.com/telefonicaid/fiware-keystone-spassword/pull/149
