### ISSUE TITLE
use python3 in docker (and upgrade to docker debian based)

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keystone-spassword#207]
Keystone stein is able to run with python3
Current docker of keystone-spassword is based on centos7 whtich uses python2.7.
https://centos.pkgs.org/7/centos-updates-x86_64/python-2.7.5-90.el7.x86_64.rpm.html

There are some approaches (from less to more difficult):
- Upgrade to use docker based in centos8
- Upgrade to use current docker but installing python3
- Create a new docker based in debian/ubuntu/alpine

Keep into acount that keystone is available in some distros (there are rpms for redhat7/redhat8) but not for others.

rdo repository for rpm based distros: https://repos.fedorapeople.org/openstack/

**Comment by fgalan** [comment]
CentOS 8 has reached end of support. Other alternatives (Debian, alpine, etc.) should be explored... in line with the overall effort of upgrades platforms components.

**Comment by AlvaroVega** [comment]
Upgrade to use current docker but installing python3:
 -> Current `openstack-keystone.rpm` depends on `python2-keystone.rpm` which depends on python2

**Comment by AlvaroVega** [comment]
Create a new docker based in debian/ubuntu/alpine
 There is a buster debian package https://packages.debian.org/buster/keystone based on keystone 14 (rocky) which uses python3

**Comment by AlvaroVega** [comment]
Done in https://github.com/telefonicaid/fiware-keystone-spassword/pull/238
