### ISSUE TITLE
RPM Compatible with mitaka version

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keystone-spassword#38]
To be compatible with Keystone mitaka version RPM must have into account that https://github.com/telefonicaid/fiware-keystone-spassword/blob/master/keystone-spassword.spec#L24 file is in /etc/keystone/keystone-paste.ini instead of /usr/share/keystone/keystone-paste-dist.ini

**Comment by AlvaroVega** [comment]
fixed in https://github.com/telefonicaid/fiware-keystone-spassword/pull/57

**Comment by fgalan** [comment]
Closeable?
