### ISSUE TITLE
users keystone crud do not shoot spassword

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keystone-spassword#72]
Users not created/deleted/updated in spassword tables when are  created/deleted/updated  in keystone tables. Related notification are not proper sent / received by middleware.

i.e.
- Create new user do not create entry in spassword table. (but it will be create after first login)
- Delete a user does not remove entry in spassword table

Probably happens since liberty version, but are minor effects

**Comment by fgalan** [comment]
Fixed by PR #71 (master) and PR #70 (release/1.4.0)
