### ISSUE TITLE
Error Keystone rebooting the docker container

### ISSUE THREAD

**Issue by amfgomez** [telefonicaid/fiware-keystone-spassword#95]
Hello.

The problem is simple:
I have a docker container with Keystone-spassword, when the container is reboot or shutdown and start, the error always appear. 
 ERROR keystone.common.wsgi [req-0c843903-63bf-4fc5-ad61-23eb9c57f184 - - - - -] No JSON object could be decoded
 ERROR keystone.common.wsgi Traceback (most recent call last):
 ERROR keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/common/wsgi.py", line 248, in __call__
 ERROR keystone.common.wsgi     result = method(context, **params)
 ERROR keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/common/controller.py", line 202, in wrapper
 ERROR keystone.common.wsgi     utils.flatten_dict(target))
 ERROR keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/policy/backends/rules.py", line 77, in enforce
 ERROR keystone.common.wsgi     enforce(credentials, action, target)
 ERROR keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/keystone/policy/backends/rules.py", line 69, in enforce
 ERROR keystone.common.wsgi     return _ENFORCER.enforce(action, target, credentials, **extra)
 ERROR keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/oslo_policy/policy.py", line 488, in enforce
 ERROR keystone.common.wsgi     self.load_rules()
 ERROR keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/oslo_policy/policy.py", line 396, in load_rules
 ERROR keystone.common.wsgi     overwrite=self.overwrite)
 ERROR keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/oslo_policy/policy.py", line 438, in _load_policy_file
 ERROR keystone.common.wsgi     rules = Rules.load_json(data, self.default_rule)
 ERROR keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/oslo_policy/policy.py", line 256, in load_json
 ERROR keystone.common.wsgi     jsonutils.loads(data).items())
 ERROR keystone.common.wsgi   File "/usr/lib/python2.7/site-packages/oslo_serialization/jsonutils.py", line 214, in loads
 ERROR keystone.common.wsgi     return json.loads(encodeutils.safe_decode(s, encoding), **kwargs)
 ERROR keystone.common.wsgi   File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
 ERROR keystone.common.wsgi     return _default_decoder.decode(s)
 ERROR keystone.common.wsgi   File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
 ERROR keystone.common.wsgi     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 ERROR keystone.common.wsgi   File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
 ERROR keystone.common.wsgi     raise ValueError("No JSON object could be decoded")
 ERROR keystone.common.wsgi ValueError: No JSON object could be decoded
 ERROR keystone.common.wsgi

**Comment by AlvaroVega** [comment]
Hi, please, could you tell us which version of Keystone docker are you using?

**Comment by amfgomez** [comment]
Hi,
Docker = 18.06.1-ce
Keystone-spassword
The following line is the response, that I got when I want to check the keystone version.
 curl -d -S http://XX.XX.XX.XX:5001/v3 | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   260  100   258  100     2  29861    231 --:--:-- --:--:-- --:--:-- 32250
{
    "error": {
        "code": 400,
        "message": "Expecting to find application/json in Content-Type header - the server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error.",
        "title": "Bad Request"
    }
}

**Comment by AlvaroVega** [comment]
version of keystone-spassword I mean

**Comment by amfgomez** [comment]
Hello @AlvaroVega 

The version of keystone-spassword is the reason. 
I believe that the keystone-spassword instances is the last version.
I have updated the keystone-spassword and the system works!!!!
